#include "Packages/jp.keijiro.bodypix/Shader/Common.hlsl"

StructuredBuffer<float4> _Keypoints;
float _Aspect;

const uint KeypointConnections[12][2] =
{
    { PART_LEFT_HIP, PART_LEFT_SHOULDER },
    { PART_LEFT_ELBOW, PART_LEFT_SHOULDER },
    { PART_LEFT_ELBOW, PART_LEFT_WRIST },
    { PART_LEFT_HIP, PART_LEFT_KNEE },
    { PART_LEFT_KNEE, PART_LEFT_ANKLE },

    { PART_RIGHT_HIP, PART_RIGHT_SHOULDER },
    { PART_RIGHT_ELBOW, PART_RIGHT_SHOULDER },
    { PART_RIGHT_ELBOW, PART_RIGHT_WRIST },
    { PART_RIGHT_HIP, PART_RIGHT_KNEE },
    { PART_RIGHT_KNEE, PART_RIGHT_ANKLE },

    { PART_LEFT_SHOULDER, PART_RIGHT_SHOULDER },
    { PART_LEFT_HIP, PART_RIGHT_HIP }
};
